"""CrewAI integration stub.

This file provides a simple `CrewAIAgent` class that acts as a wrapper for
calling an agent orchestration system (CrewAI or similar). It's a scaffold:
replace the `call_agent` implementation with an actual HTTP/client call to
CrewAI, supplying your API key and payload.

Example usage:
from crewai_agent import CrewAIAgent
agent = CrewAIAgent(api_key="YOUR_KEY")
agent.suggest_groups(db_path, {"prompt": "create 2 study groups"})

If you have a CrewAI SDK, use it here. Otherwise implement HTTP call to the agent
endpoint.

For demo purposes, the `suggest_groups` method gathers context and returns
a reasonable heuristic suggestion without calling an external service.

"""
import json
from models import session_scope, Student
from matching import match_for_student

class CrewAIAgent:
    def __init__(self, api_key=None):
        self.api_key = api_key or "<YOUR_CREWAI_KEY>"

    def call_agent(self, context):
        # TODO: Replace this stub with real CrewAI API/SDK invocation.
        # Example (pseudo):
        # response = requests.post("https://api.crewai.example/run", headers={...}, json=context)
        # return response.json()
        return {"note": "This is a stub — implement CrewAI API call here", "context_sample": context}

    def suggest_groups(self, db_path, payload=None):
        # payload may include requested group size, objectives, etc.
        # We'll produce a simple suggestion using matching logic as a fallback.
        with session_scope(db_path) as session:
            students = session.query(Student).all()
            # Build lightweight context
            ctx = [s.to_dict() for s in students]
        # Optionally call real agent:
        # return self.call_agent({ "students": ctx, "payload": payload })
        # Fallback heuristic: for each student, return top 2 matches
        suggestions = {str(s["id"]): match_for_student(db_path, s["id"], top_n=2) for s in ctx}
        return { "suggestions": suggestions, "note": "Generated by local heuristic (CrewAI stub)" }
